default:
  image: xlxs4/gnuradio:latest

build:
  script:
    - cd gr-a3sat
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - make
    - make install
    - ldconfig
    - cd ..

  artifacts:
    paths:
      - gr-a3sat/build/

test:
  stage: test
  needs: ["build"]
  script:
    - cd gr-a3sat/build
    - make CTEST_OUTPUT_ON_FAILURE=1 test