/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-a3sat
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_A3SAT_API_H
#define INCLUDED_A3SAT_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_a3sat_EXPORTS
#define A3SAT_API __GR_ATTR_EXPORT
#else
#define A3SAT_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_A3SAT_API_H */
